# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [23]:
from sklearn import model_selection as cross_validation
from sklearn import datasets
import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [24]:
iris = datasets.load_iris()

In [25]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [26]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [27]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [28]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[5.8 2.7 5.1 1.9]
 [5.  2.  3.5 1. ]
 [5.1 3.5 1.4 0.3]
 [7.7 2.8 6.7 2. ]
 [6.  2.7 5.1 1.6]]


Тестовая выборка:
[[4.6 3.1 1.5 0.2]
 [6.3 2.9 5.6 1.8]
 [7.3 2.9 6.3 1.8]
 [6.7 3.1 5.6 2.4]
 [6.  3.4 4.5 1.6]]


In [29]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[2 1 0 2 1 2 1 0 2 2 0 2 1 2 0 0 2 2 1 2 0 1 1 2 1 1 2 0 1 1 2 0 2 1 2 1 0
 0 1 0 2 2 0 2 0 2 0 0 0 0 2 1 0 0 0 2 1 1 0 2 0 2 0 0 2 0 0 1 1 1 1 1 0 2
 1 0 0 0 2 0 2 1 2 1 1 2 1 2 2 2 2 2 1 1 0 0 2 2 2 1 1 1 2 2 2]


Метки классов на тестовой выборке:
[0 2 2 2 1 1 0 0 1 0 1 0 2 1 1 1 0 0 0 2 0 2 0 0 1 1 1 1 1 1 0 1 0 1 1 2 0
 2 0 1 0 0 2 1 2]


### Стратегии проведения кросс-валидации

#### KFold

In [34]:
X = range(10)
print X

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [37]:
for train_indices, test_indices in cross_validation.KFold(n_splits = 2).split(X):
    print train_indices, test_indices

[5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4] [5 6 7 8 9]


In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True):
    print train_indices, test_indices

In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

#### StratifiedKFold

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print train_indices, test_indices

In [ ]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print train_indices, test_indices

#### ShuffleSplit

In [ ]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    print train_indices, test_indices

#### StratifiedShuffleSplit

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

#### Leave-One-Out

In [ ]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators